import math
import turtle

a=input("Nume angajator:")
b=int(input("Nr ore/saptamana:"))
c=int(input("Plata/ora lucrata:"))
d=int(input("CAS:"))
e=int(input("CASS:"))
f=int(input("Impozit pe venit:"))

CAS=d/100
CASS=e/100
Ipv=f/100
Slb=(b*4)*c
SlbCAS=((b*4)*c)*(d/100)
SlbCASS=((b*4)*c)*(e/100)
Slbipv=((b*4)*c)*(f/100)

Sln=Slb-SlbCAS-SlbCASS-Slbipv

print("Salariul net oferit de",a,"este de",math.ceil(Sln),"lei.")

if Sln<1900:
    print(math.ceil(Sln),"lei","reprezinta un trai scazut.")
elif Sln>=1900 and Sln<3001:
    print(math.ceil(Sln),"lei","reprezinta un trai mediocru.")
elif Sln>=3001 and Sln<3801:
    print(math.ceil(Sln),"lei","reprezinta un trai mediu.")
elif Sln>=3801 and Sln<5001:
    print(math.ceil(Sln),"lei","reprezinta un trai peste medie.")
elif Sln>=4001:
    print(math.ceil(Sln),"lei","reprezinta un trai ridicat.")

g=turtle.Turtle()
g.pensize(3)
g.speed(10)
g.begin_fill()
g.color("blue")
g.circle(100,steps=30)
g.penup()
g.setposition(0,90)
g.pendown()
g.end_fill()
g.begin_fill()
g.color("lightblue")
g.write(a,align="center",font=("Arial",35,"bold"))
g.end_fill()

h=turtle.Turtle()
h.pensize(3)
h.speed(10)
h.penup()
h.setposition(-180,-160)
h.pendown()
h.begin_fill()
h.color("green")
h.circle(62,steps=5)
h.end_fill()
h.begin_fill()
h.color("black")
h.penup()
h.setposition(-200,-120)
h.pendown()
h.write(b,align="center",font=("Times",30,"bold"))
h.end_fill()
h.begin_fill()
h.color("black")
h.penup()
h.setposition(-177,-119)
h.pendown()
h.write("h/s",align="left",font=("Times",28,"bold"))
h.end_fill()

i=turtle.Turtle()
i.pensize(3)
i.speed(10)
i.penup()
i.setposition(180,-160)
i.pendown()
i.begin_fill()
i.color("green")
i.circle(62,steps=5)
i.end_fill()
i.begin_fill()
i.color("black")
i.penup()
i.setposition(153,-120)
i.pendown()
i.write(c,align="center",font=("Times",30,"bold"))
i.end_fill()
i.begin_fill()
i.color("black")
i.penup()
i.setposition(176,-119)
i.pendown()
i.write("lei/h",align="left",font=("Times",28,"bold"))
i.end_fill()

j=turtle.Turtle()
j.pensize(3)
j.speed(10)
j.penup()
j.setposition(-160,-310)
j.pendown()
j.begin_fill()
j.color("red")
j.circle(62,steps=4)
j.end_fill()
j.begin_fill()
j.color("lime")
j.penup()
j.setposition(-172,-270)
j.pendown()
j.write(d,align="center",font=("Times",30,"bold"))
j.end_fill()
j.begin_fill()
j.color("black")
j.penup()
j.setposition(-156,-270)
j.pendown()
j.write("%",align="left",font=("Times",30,"bold"))
j.end_fill()

k=turtle.Turtle()
k.pensize(3)
k.speed(10)
k.penup()
k.setposition(0,-310)
k.pendown()
k.begin_fill()
k.color("red")
k.circle(62,steps=4)
k.end_fill()
k.begin_fill()
k.color("blue")
k.penup()
k.setposition(-11,-270)
k.pendown()
k.write(e,align="center",font=("Times",30,"bold"))
k.end_fill()
k.begin_fill()
k.color("yellow")
k.penup()
k.setposition(5,-270)
k.pendown()
k.write("%",align="left",font=("Times",30,"bold"))
k.end_fill()

l=turtle.Turtle()
l.pensize(3)
l.speed(10)
l.penup()
l.setposition(160,-310)
l.pendown()
l.begin_fill()
l.color("red")
l.circle(62,steps=4)
l.end_fill()
l.begin_fill()
l.color("blue")
l.penup()
l.setposition(148,-270)
l.pendown()
l.write(f,align="center",font=("Times",30,"bold"))
l.end_fill()
l.begin_fill()
l.color("blue")
l.penup()
l.setposition(164,-270)
l.pendown()
l.write("%",align="left",font=("Times",30,"bold"))
l.end_fill()

m=turtle.Turtle()
m.pensize(3)
m.speed(10)
m.penup()
m.setposition(0,-177)
m.pendown()
m.begin_fill()
m.color("black")
m.circle(80,steps=20)
m.end_fill()
m.begin_fill()
m.color("white")
m.penup()
m.setposition(-21,-115)
m.pendown()
m.write(math.ceil(Sln),align="center",font=("Arial",36,"bold"))
m.end_fill()
m.begin_fill()
m.color("white")
m.penup()
m.setposition(29,-116)
m.pendown()
m.write("lei",align="left",font=("Arial",36,"bold"))
m.end_fill()

n=turtle.Turtle()
n.pensize(2)
n.speed(10)
n.penup()
n.setposition(2,-20)
n.pendown()
n.write("Salariu net/luna",align="center",font=("Arial",18,"bold"))

turtle.done()
